paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos existentes
      tags:
        - Productos
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Los productos fueron obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno del servidor, usualmente obtenido por una consulta defectuosa
        "403":
          description: El token de acceso recibido en la cabecera es inválido
    post:
      summary: Crea un nuevo producto
      tags:
        - Productos
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Producto"
      responses:
        "200":
          description: Producto creado exitosamente
        "400":
          description: Se produjo un error al crear el producto, la metadata del producto enviada no respeta las reglas de negocio establecidas
        "500":
          description: Error interno del servidor, usualmente obtenido por una consulta defectuosa
        "403":
          description: El token de acceso recibido en la cabecera es inválido
  /api/products/{pid}:
    get:
      summary: Obtiene un producto según su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto a solicitar.
          schema:
            $type: String
      security:
        - BearerAuth: []
      responses:
        "200":
          description: El producto fue obtenido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno del servidor, usualmente obtenido por una consulta defectuosa
        "403":
          description: El token de acceso recibido en la cabecera es inválido
    put:
      summary: Modifica un producto existente
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto a solicitar.
          schema:
            $type: String
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrearProducto"
      responses:
        "200":
          description: El producto fue modificado correctamente
        "400":
          description: Se produjo un error al crear el producto, la metadata del producto enviada no respeta las reglas de negocio establecidas
        "500":
          description: Error interno del servidor, usualmente obtenido por una consulta defectuosa
        "403":
          description: El token de acceso recibido en la cabecera es inválido
    delete:
      summary: Elimina un producto según su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto a eliminar.
          schema:
            $type: String
      security:
        - BearerAuth: []
      responses:
        "200":
          description: El producto fue eliminado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno del servidor, usualmente obtenido por una consulta defectuosa
        "403":
          description: El token de acceso recibido en la cabecera es inválido
################################################################################################################

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Producto:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        code:
          type: string
          description: Abreviatura que define unívocamente a cada producto
        description:
          type: string
          description: Detalles adicionales del producto
        category:
          type: string
          description: Clasificación que se le asigna al producto según su uso
        price:
          type: number
          description: Valor del producto expresado en moneda local
        stock:
          type: number
          description: Cantidad disponible para la venta
        owner:
          type: string
          description: E-mail del usuario que es propietario del producto
        status:
          type: boolean
          description: Indica si el producto se encuentra en venta (true para "sí", false para "no")
        thumbnails:
          type: array
          description: Arreglo que contiene los hipervínculos correspondientes a todas las imágenes disponibles para el producto
      example:
        _id: ObjectId('64550c96def1d16c4d481fb1')
        title: Nightwing - Saltando a la luz
        code: zxw1
        description: Producto modificado nuevamente
        category: Comicbook
        price: 33
        stock: 93
        owner: "andresgabriel.92@gmail.com"
        status: true
        thumbnails:
          [
            https://d3ugyf2ht6aenh.cloudfront.net/stores/001/184/069/products/nightwing_cov11-74d2c8a8c0f545614c16635595218442-640-0.webp,
          ]

    CrearProducto:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        code:
          type: string
          description: Abreviatura que define unívocamente a cada producto
        description:
          type: string
          description: Detalles adicionales del producto
        category:
          type: string
          description: Clasificación que se le asigna al producto según su uso
        price:
          type: number
          description: Valor del producto expresado en moneda local
        stock:
          type: number
          description: Cantidad disponible para la venta
        status:
          type: boolean
          description: Indica si el producto se encuentra en venta (true para "sí", false para "no")
        thumbnails:
          type: array
          description: Arreglo que contiene los hipervínculos correspondientes a todas las imágenes disponibles para el producto
      example:
        title: Nightwing - Saltando a la luz
        code: zxw1
        description: Producto modificado nuevamente
        category: Comicbook
        price: 33
        stock: 93
        status: true
        thumbnails:
          [
            https://d3ugyf2ht6aenh.cloudfront.net/stores/001/184/069/products/nightwing_cov11-74d2c8a8c0f545614c16635595218442-640-0.webp,
          ]
